openapi: 3.0.0
x-stoplight:
  id: xxxxxxxx
info:
  title: open-api-spec
  version: "1.0"
tags:
  - name: todo
    description: todoに関するエンドポイント
  - name: user
    description: ユーザーに関するエンドポイント

servers:
  - url: "http://localhost:8080/v1"
paths:
  /users:
    $ref: "./user/path.yaml#/users"
  /users/{userId}:
    $ref: "./user/path.yaml#/users_userId"
  /todos/{userId}:
    $ref: "./todo/path.yaml#/todos_userId"

components:
  schemas:
    user:
      $ref: "./user/schema.yaml#/user"
    todo:
      $ref: "./todo/schame.yaml#/todo"
    error:
      $ref: "./components/schema/error.yaml#/error"

  responses:
    BadRequestResponse:
      $ref: "./components/response/response.yaml#/BadRequestResponse"
    UnauthorizedResponse:
      $ref: "./components/response/response.yaml#/UnauthorizedResponse"
    ForbiddenResponse:
      $ref: "./components/response/response.yaml#/ForbiddenResponse"
    NotFoundResponse:
      $ref: "./components/response/response.yaml#/NotFoundResponse"
    InternalServerErrorResponse:
      $ref: "./components/response/response.yaml#/InternalServerErrorResponse"
