# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/main/configuration-schema.json
package: openapi
generate:
  echo-server: true
  models: true
  embedded-spec: true
output: ./openapi.gen.go
